import os

class Config(object):
    SECRET_KEY = os.environ.get("SECRET_KEY")
    GOOGLE_APPLICATION_CREDENTIALS = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
    GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID")
    GOOGLE_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET")
    GOOGLE_PROJECT_ID = os.environ.get("GOOGLE_PROJECT_ID")
    GOOGLE_PROJECT_STORAGE_BUCKET = os.environ.get("GOOGLE_PROJECT_STORAGE_BUCKET")